### ISSUE TITLE
This looks great! 

### ISSUE THREAD

**Issue by MostHated** [SkaillZ/ubernet#1]
Hey there,
    I just came across this, from the little bit I looked over it, it looks fantastic. I see that it also implements Photon, is that just for matchmaking? I am not a big fan of Photon, but am of LiteNet and UniRx. Once I have some time, I will be going over this a lot more thoroughly. 

Thanks,
-MH

**Comment by SkaillZ** [comment]
Hey,

basically, the idea behind Ubernet is creating a united interface for an unlimited number of providers, so you could have a Matchmaker implemented with Photon, another one for LAN matchmaking etc.

An important feature I have planned is being able to "upgrade" your Photon connection to a peer-to-peer connection once it's established, so you could find matches with Photon and if possible, connect with LiteNetLib after matchmaking.

Keep in mind that LiteNetLib support is in a _very_ early stage right now and can only handle up to 2 players. I'll improve when I have more time, but even right now it's very useful for local testing with two clients without having to connect to the internet (like you would have to do normally when developing games with the Photon SDK).

Thanks for the feedback!
-SkaillZ
